name: test checkout
on: push
jobs:
  build:
    runs-on: custom-label
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
        echo Hello, world!
        ls -al
        echo "Org Level self-hosted runner test new"
